import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Family } from '@/shared/api-client/api';
import { useAuthStore } from '@/features/auth/auth-store';

export default function Home() {
 const {token,user,hydrated,signOut}=useAuthStore(); const [families,setFamilies]=useState<Family[]>([]);
 useEffect(()=>{if(hydrated&&!token)router.replace('/login'); if(token)api.families(token).then(setFamilies).catch(()=>{});},[hydrated,token]);
 if(!hydrated||!token)return <View style={s.loading}><ActivityIndicator/></View>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>MEMORA</Text><Text style={s.title}>Hello, {user?.displayName}</Text></View><Pressable onPress={async()=>{await signOut();router.replace('/login')}}><Text style={s.logout}>Sign out</Text></Pressable></View>
 <View style={s.hero}><Text style={s.heroTitle}>Every story deserves to be remembered.</Text><Text style={s.heroText}>Preserve the voices, moments and stories that make your family yours.</Text><View style={s.actions}><Pressable style={s.primary} onPress={()=>router.push('/family')}><Text style={s.primaryText}>Family spaces</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/profiles')}><Text style={s.secondaryText}>Profiles</Text></Pressable></View></View>
 <Text style={s.section}>Your family</Text>{families.length===0?<View style={s.card}><Text style={s.cardTitle}>Create your first family space</Text><Text style={s.muted}>A private home for the people and memories you care about.</Text><Pressable onPress={()=>router.push('/family')}><Text style={s.link}>Get started →</Text></Pressable></View>:families.map(f=><View key={f.id} style={s.card}><Text style={s.cardTitle}>{f.name}</Text><Text style={s.muted}>Ready for memories and profiles</Text></View>)}
 <Text style={s.section}>Coming next</Text><View style={s.card}><Text style={s.cardTitle}>Memory timeline</Text><Text style={s.muted}>Photos, stories, voice and video will come together here in Phase 4.</Text></View></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},safe:{flex:1,backgroundColor:'#F7F3EC'},content:{padding:22,gap:16},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:2,color:'#8A6F5B'},title:{fontSize:28,fontWeight:'800',color:'#211B17',marginTop:4},logout:{color:'#765D4B',fontWeight:'700'},hero:{backgroundColor:'#5D493B',padding:24,borderRadius:24,gap:12},heroTitle:{fontSize:28,lineHeight:34,fontWeight:'800',color:'#FFF9F2'},heroText:{fontSize:16,lineHeight:23,color:'#E9DED4'},actions:{flexDirection:'row',gap:10,marginTop:5},primary:{backgroundColor:'#FFF9F2',paddingHorizontal:18,paddingVertical:13,borderRadius:14},primaryText:{color:'#5D493B',fontWeight:'800'},secondary:{borderWidth:1,borderColor:'#D9C9BC',paddingHorizontal:18,paddingVertical:13,borderRadius:14},secondaryText:{color:'#FFF9F2',fontWeight:'800'},section:{fontSize:20,fontWeight:'800',color:'#211B17',marginTop:6},card:{backgroundColor:'#fff',padding:18,borderRadius:18,gap:7},cardTitle:{fontSize:18,fontWeight:'800',color:'#211B17'},muted:{color:'#786A61',lineHeight:21},link:{color:'#6B5545',fontWeight:'800',marginTop:5}});
