import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Memory, MemoryProfile } from '@/shared/api-client/api'; import { useAuthGuard } from '@/features/auth/use-auth-guard';
export default function MemoryEdit(){const {id,familyId}=useLocalSearchParams<{id:string;familyId:string}>();const {token,ready}=useAuthGuard();const [memory,setMemory]=useState<Memory|null>(null);const [title,setTitle]=useState('');const [story,setStory]=useState('');const [date,setDate]=useState('');const [profiles,setProfiles]=useState<MemoryProfile[]>([]);const [profileId,setProfileId]=useState<string|undefined>();const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!ready||!token||!familyId)return;Promise.all([api.memories(token,familyId),api.profiles(token,familyId)]).then(([ms,ps])=>{const m=ms.find(x=>x.id===id)??null;setMemory(m);setProfiles(ps);if(m){setTitle(m.title);setStory(m.story);setDate(m.occurredAt?m.occurredAt.slice(0,10):'');setProfileId(m.profileId);}}).catch(e=>setError(e instanceof Error?e.message:'Unable to load memory'));},[ready,id,familyId,token]);
 const save=async()=>{if(!token||!id||!title.trim()||!story.trim())return;setSaving(true);setError('');try{await api.updateMemory(token,id,{title:title.trim(),story:story.trim(),occurredAt:date.trim()?new Date(date.trim()).toISOString():undefined,profileId});router.replace({pathname:'/memory-detail' as any,params:{id,familyId}});}catch(e){setError(e instanceof Error?e.message:'Unable to update memory');}finally{setSaving(false);}};
 if(!ready||(!memory&&!error))return <View style={s.loading}><ActivityIndicator/></View>;
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.title}>Edit memory</Text><View style={s.form}><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Memory title"/><TextInput style={[s.input,s.story]} multiline textAlignVertical="top" value={story} onChangeText={setStory} placeholder="Tell the story..."/><TextInput style={s.input} value={date} onChangeText={setDate} placeholder="Date (YYYY-MM-DD)"/><Text style={s.label}>Person</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable style={[s.chip,!profileId&&s.selected]} onPress={()=>setProfileId(undefined)}><Text>Family</Text></Pressable>{profiles.map(p=><Pressable key={p.id} style={[s.chip,profileId===p.id&&s.selected]} onPress={()=>setProfileId(p.id)}><Text>{p.displayName}</Text></Pressable>)}</ScrollView>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.button} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Save changes</Text>}</Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},safe:{flex:1,backgroundColor:'#F7F3EC'},flex:{flex:1},content:{padding:22,gap:14,paddingBottom:50},back:{fontSize:17,fontWeight:'700',color:'#6B5545'},title:{fontSize:30,fontWeight:'800',color:'#211B17'},form:{backgroundColor:'#fff',padding:17,borderRadius:20,gap:11},input:{borderWidth:1,borderColor:'#DED6CF',borderRadius:13,padding:14,fontSize:16,backgroundColor:'#FCFBF9'},story:{minHeight:170},label:{fontWeight:'800',color:'#44372E'},chips:{gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:18,backgroundColor:'#F2ECE6'},selected:{borderWidth:2,borderColor:'#6B5545'},error:{color:'#B42318'},button:{backgroundColor:'#6B5545',padding:15,borderRadius:13,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'}});