import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, MemoryProfile } from '@/shared/api-client/api'; import { useAuthGuard } from '@/features/auth/use-auth-guard';
export default function MemoryForm(){const {familyId,profileId:initialProfileId}=useLocalSearchParams<{familyId:string;profileId?:string}>();const {token,ready}=useAuthGuard();const [title,setTitle]=useState('');const [story,setStory]=useState('');const [date,setDate]=useState('');const [profiles,setProfiles]=useState<MemoryProfile[]>([]);const [profileId,setProfileId]=useState<string|undefined>(initialProfileId);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(ready&&token&&familyId)api.profiles(token,familyId).then(setProfiles).catch(()=>{});},[ready,familyId,token]);
 const save=async()=>{if(!token||!familyId||!title.trim()||!story.trim()){setError('Title and story are required.');return;}setLoading(true);setError('');try{await api.createMemory(token,familyId,{title:title.trim(),story:story.trim(),occurredAt:date.trim()?new Date(date.trim()).toISOString():undefined,profileId});initialProfileId ? router.back() : router.replace('/memories' as any);}catch(e){setError(e instanceof Error?e.message:'Unable to save memory');}finally{setLoading(false);}};
 if(!ready)return <View style={s.loading}><ActivityIndicator/></View>;
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.title}>Add a memory</Text><Text style={s.sub}>Write down a moment you never want your family to lose.</Text><View style={s.form}><TextInput style={s.input} placeholder="Memory title" value={title} onChangeText={setTitle}/><TextInput style={[s.input,s.story]} placeholder="Tell the story..." multiline textAlignVertical="top" value={story} onChangeText={setStory}/><TextInput style={s.input} placeholder="Date (YYYY-MM-DD, optional)" value={date} onChangeText={setDate}/><Text style={s.label}>Person (optional)</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable style={[s.chip,!profileId&&s.selected]} onPress={()=>setProfileId(undefined)}><Text>Family</Text></Pressable>{profiles.map(p=><Pressable key={p.id} style={[s.chip,profileId===p.id&&s.selected]} onPress={()=>setProfileId(p.id)}><Text>{p.displayName}</Text></Pressable>)}</ScrollView>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.button} onPress={save} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Save memory</Text>}</Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},safe:{flex:1,backgroundColor:'#F7F3EC'},flex:{flex:1},content:{padding:22,gap:14,paddingBottom:50},back:{fontSize:17,fontWeight:'700',color:'#6B5545'},title:{fontSize:30,fontWeight:'800',color:'#211B17'},sub:{fontSize:16,color:'#74675E',lineHeight:22},form:{backgroundColor:'#fff',padding:17,borderRadius:20,gap:11},input:{borderWidth:1,borderColor:'#DED6CF',borderRadius:13,padding:14,fontSize:16,backgroundColor:'#FCFBF9'},story:{minHeight:150},label:{fontWeight:'800',color:'#44372E'},chips:{gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:18,backgroundColor:'#F2ECE6'},selected:{borderWidth:2,borderColor:'#6B5545'},error:{color:'#B42318'},button:{backgroundColor:'#6B5545',padding:15,borderRadius:13,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'}});