import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Family, Memory } from '@/shared/api-client/api';
import { useAuthGuard } from '@/features/auth/use-auth-guard';

export default function Memories(){
 const {token,ready}=useAuthGuard(); const [family,setFamily]=useState<Family|null>(null); const [items,setItems]=useState<Memory[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{if(!ready||!token)return;(async()=>{try{const fs=await api.families(token);const f=fs[0]??null;setFamily(f);if(f)setItems(await api.memories(token,f.id));}catch(e){setError(e instanceof Error?e.message:'Unable to load memories');}finally{setLoading(false);}})();},[ready,token]);
 if(!ready)return <View style={s.loading}><ActivityIndicator/></View>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.replace('/' as any)}><Text style={s.back}>‹ Home</Text></Pressable>{family&&<Pressable style={s.add} onPress={()=>router.push({pathname:'/memory-form' as any,params:{familyId:family.id}})}><Text style={s.addText}>+ Memory</Text></Pressable>}</View><Text style={s.title}>Memory timeline</Text><Text style={s.sub}>{family?family.name:'Create a family space before adding memories.'}</Text>{!!error&&<Text style={s.error}>{error}</Text>}{loading?<ActivityIndicator/>:items.length===0&&family?<View style={s.empty}><Text style={s.emptyTitle}>Your story starts here</Text><Text style={s.sub}>Add a first memory, moment or family story.</Text></View>:items.map(m=><Pressable key={m.id} style={s.card} onPress={()=>router.push({pathname:'/memory-detail' as any,params:{id:m.id,familyId:m.familyId}})}><Text style={s.date}>{m.occurredAt?new Date(m.occurredAt).toLocaleDateString():'Date not set'}</Text><Text style={s.cardTitle}>{m.title}</Text><Text style={s.story} numberOfLines={3}>{m.story}</Text>{m.profile&&<Text style={s.person}>Remembering {m.profile.displayName}</Text>}</Pressable>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},safe:{flex:1,backgroundColor:'#F7F3EC'},content:{padding:22,gap:14},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{fontSize:17,fontWeight:'700',color:'#6B5545'},add:{backgroundColor:'#6B5545',paddingHorizontal:15,paddingVertical:10,borderRadius:13},addText:{color:'#fff',fontWeight:'800'},title:{fontSize:30,fontWeight:'800',color:'#211B17'},sub:{fontSize:16,color:'#74675E',lineHeight:22},error:{color:'#B42318'},empty:{backgroundColor:'#fff',padding:22,borderRadius:20,gap:6},emptyTitle:{fontSize:19,fontWeight:'800',color:'#211B17'},card:{backgroundColor:'#fff',padding:18,borderRadius:20,gap:7},date:{fontSize:12,fontWeight:'800',color:'#9A7D67',textTransform:'uppercase'},cardTitle:{fontSize:20,fontWeight:'800',color:'#211B17'},story:{color:'#6F6259',lineHeight:21},person:{color:'#6B5545',fontWeight:'700',marginTop:3}});