import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Family, MemoryProfile } from '@/shared/api-client/api';
import { useAuthGuard } from '@/features/auth/use-auth-guard';
export default function Profiles(){
 const {token,ready}=useAuthGuard(); const [family,setFamily]=useState<Family|null>(null); const [items,setItems]=useState<MemoryProfile[]>([]); const [name,setName]=useState(''); const [relationship,setRelationship]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{if(!token)return;const fs=await api.families(token);const f=fs[0]??null;setFamily(f);if(f)setItems(await api.profiles(token,f.id));setLoading(false);};
 // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect -- `load` is a plain closure recreated every render; the .catch() setState only fires async on rejection, not synchronously within the effect.
 useEffect(()=>{if(ready)load().catch(e=>{setError(e instanceof Error?e.message:'Unable to load profiles');setLoading(false);});},[ready]);
 const create=async()=>{if(!token||!family||!name.trim())return;try{await api.createProfile(token,family.id,{displayName:name.trim(),relationship:relationship.trim()||undefined,preferredLanguage:'en',spokenLanguages:['en']});setName('');setRelationship('');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to add profile');}};
 if(!ready)return <View style={s.loading}><ActivityIndicator/></View>;
 return <SafeAreaView style={s.safe}><Pressable style={s.back} onPress={()=>router.replace('/' as any)}><Text style={s.backText}>‹ Home</Text></Pressable><Text style={s.title}>Memory profiles</Text><Text style={s.sub}>{family ? 'People remembered in '+family.name : 'Create a family space first.'}</Text>{family&&<View style={s.form}><TextInput style={s.input} placeholder="Person's name" value={name} onChangeText={setName}/><TextInput style={s.input} placeholder="Relationship (optional)" value={relationship} onChangeText={setRelationship}/><Pressable style={s.button} onPress={create}><Text style={s.buttonText}>Add profile</Text></Pressable></View>}{!!error&&<Text style={s.error}>{error}</Text>}{loading?<ActivityIndicator/>:items.map(p=><View key={p.id} style={s.card}><View style={s.avatar}><Text style={s.initial}>{p.displayName[0]?.toUpperCase()}</Text></View><View><Text style={s.name}>{p.displayName}</Text><Text style={s.meta}>{(p.relationship||'Family member')+' • '+p.status}</Text></View></View>)}</SafeAreaView>;
}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},safe:{flex:1,backgroundColor:'#F7F3EC',padding:22,gap:14},back:{alignSelf:'flex-start',paddingVertical:8,paddingRight:16},backText:{fontSize:17,fontWeight:'700',color:'#6B5545'},title:{fontSize:30,fontWeight:'800',color:'#211B17'},sub:{fontSize:16,color:'#74675E'},form:{gap:9,backgroundColor:'#fff',padding:16,borderRadius:18},input:{borderWidth:1,borderColor:'#DED6CF',borderRadius:13,padding:13},button:{backgroundColor:'#6B5545',padding:14,borderRadius:13,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},error:{color:'#B42318'},card:{backgroundColor:'#fff',padding:15,borderRadius:18,flexDirection:'row',alignItems:'center',gap:13},avatar:{width:46,height:46,borderRadius:23,backgroundColor:'#E9DED4',alignItems:'center',justifyContent:'center'},initial:{fontSize:19,fontWeight:'800',color:'#5D493B'},name:{fontSize:17,fontWeight:'800',color:'#211B17'},meta:{color:'#81736A',marginTop:3}});
